version: '2'
services:
    emiratesgrponlineshop-app:
        image: emiratesgrponlineshop
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://emiratesgrponlineshop-mysql:3306/emiratesgrponlineshop?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    emiratesgrponlineshop-mysql:
        extends:
            file: mysql.yml
            service: emiratesgrponlineshop-mysql
